### ISSUE TITLE
mod id duplicate

### ISSUE THREAD

**Issue by icidle** [modmuss50/StructureUtils2#1]
just wanted to let you know im getting a mod id conflict between structure utils and bark 1.0.0 for 1.14.4

**Comment by icidle** [comment]
in case you need this:


Caused by: net.fabricmc.loader.discovery.ModResolutionException: Duplicate versions for mod ID 'modid': [2.0.0 at /C:/Program%20Files%20(x86)/mmc-stable-win32/MultiMC/instances/1.14.41/.minecraft/mods/structure_utils-2.0.0.jar], [1.0.0 at /C:/Program%20Files%20(x86)/mmc-stable-win32/MultiMC/instances/1.14.41/.minecraft/mods/bark-1.0.0.jar]
	at net.fabricmc.loader.discovery.ModCandidateSet.toSortedSet(ModCandidateSet.java:87)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:112)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:504)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:145)
